---
ID: "07269451-4d2e-4c5f-b52c-0854cbbe9cc2"
Parent: "3a9df4c4-cf57-4bb3-a6e2-105ab37820b0"
Template: "3a9df4c4-cf57-4bb3-a6e2-105ab37820b0"
Path: /sitecore/templates/Project/Group/Page Types/Event/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170509T130231Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
